// Required by Webpack - do not touch
require.context('../', true, /\.(html|json|txt|dat)$/i)
require.context('../images/', true, /\.(gif|jpg|png|svg|eot|ttf|woff|woff2)$/i)
require.context('../stylesheets/', true, /\.(css|scss)$/i)

// First: Set up your name
let std_name = "Alexandrew Christensen"
document.querySelector('#std_name').innerHTML = `<strong>${std_name}</strong>`

//Then: comes everything else
// TODO
import * as d3 from "d3";

// <svg width="500" height="600" style="background: rgb(232, 207, 207)" fill="transparent">d3.select('main')
let svg1 = d3.select('main').append('svg')
    .attr('width', 100)
    .attr('height', 100)
    .style('background', '#eee')
    .style('fill', 'transparent')
let svg2 = d3.select('main').append('svg')
    .attr('width', 100)
    .attr('height', 100)
    .style('background', '#eee')
    .style('fill', 'transparent')
let svg3 = d3.select('main').append('svg')
    .attr('width', 100)
    .attr('height', 100)
    .style('background', '#eee')
    .style('fill', 'transparent')
let svg4 = d3.select('main').append('svg')
    .attr('width', 100)
    .attr('height', 100)
    .style('background', '#eee')
    .style('fill', 'transparent')
let svg5 = d3.select('main').append('svg')
    .attr('width', 100)
    .attr('height', 100)
    .style('background', '#eee')
    .style('fill', 'transparent')
let obj_circle = svg1.append('circle')
    .attr('cx', 50)
    .attr('cy', 50)
    .attr('r', 50)
    .attr('stroke', 'black')
    .attr('fill', 'transparent')
let Rect_svg1 = svg1.append('rect')
    .attr('x', 50)
    .attr('y', 50)
    .attr('rx', 50)
    .attr('ry', 50)
    .attr('width', .25)
    .attr('height', 40)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let interpol_rotate = d3.interpolateString('rotate(0, 50, 50)', 'rotate(360, 50, 50)')
function animate_rect()
{
    Rect_svg1
        .transition()
        // .attr('transform', 'translate(50, 50)')
        // .duration(1000)
        .attrTween('transform', function(d,i,a){return interpol_rotate})
        .duration(5000)
        .on('end',animate_rect)
    //repeatCount="indefinite"

}
animate_rect()

let obj_circle2 = svg2.append('circle')
    .attr('cx', 50)
    .attr('cy', 50)
    .attr('r', 50)
    .attr('stroke', 'black')
    .attr('fill', 'transparent')
let eye1 = svg2.append('rect')
    .attr('x', 30)
    .attr('y', 30)
    .attr('width', 1)
    .attr('height', 1)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let eye2 = svg2.append('rect')
    .attr('x', 70)
    .attr('y', 30)
    .attr('width', 1)
    .attr('height', 1)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let half_circle = svg2.append('circle')
    .attr('cx', 50)
    .attr('cy', 50)
    .attr('r', 50)
    .attr('stroke', 'black')
    .attr('fill', 'transparent')
function ani_circles_svg2(){
    let rotatec1 = d3.interpolateString('rotate(0, 30, 30)', 'rotate(360, 30, 30)')
    let rotatec2 = d3.interpolateString('rotate(0, 70, 30)', 'rotate(360, 70, 30)')
    obj_circle2
        .transition()
        .attrTween('transform', function(d,i,a){return rotatec1})
        .duration(2000)
    half_circle
        .transition()
        .attrTween('transform', function(d,i,a){return rotatec2})
        .duration(2000)
        .on('end', ani_circles_svg2)
}
ani_circles_svg2()



let left_piller = svg3.append('rect')
    .attr('x', 25)
    .attr('y', 20)
    .attr('width', 5)
    .attr('height', 60)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let cen_piller1 = svg3.append('rect')
    .attr('x', 45)
    .attr('y', 20)
    .attr('width', 5)
    .attr('height', 60)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let cen_piller2 = svg3.append('rect')
    .attr('x', 65)
    .attr('y', 20)
    .attr('width', 5)
    .attr('height', 60)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let right_piller = svg3.append('rect')
    .attr('x', 85)
    .attr('y', 20)
    .attr('width', 5)
    .attr('height', 60)
    .attr('stroke', 'black')
    .attr('fill', 'black')

let floor = svg3.append('rect')
    .attr('x', 20)
    .attr('y', 85)
    .attr('width', 75)
    .attr('height', 5)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let roof = svg3.append('rect')
    .attr('x', 20)
    .attr('y', 10)
    .attr('width', 75)
    .attr('height', 5)
    .attr('stroke', 'black')
    .attr('fill', 'black')
function animate_svg3(){
    svg3.transition()
        .attr('transform','translate(0,2)')
        .duration(25)
        .delay(25)
        .transition()
        .attr('transform','translate(0,-2)')
        .duration(25)
        .on('end',animate_svg3)
}
animate_svg3()


let table_top = svg4.append('rect')
    .attr('x', 20)
    .attr('y', 50)
    .attr('width', 75)
    .attr('height', 2)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let leg_left = svg4.append('rect')
    .attr('x', 20)
    .attr('y', 57)
    .attr('width', 5)
    .attr('height', 30)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let leg_right = svg4.append('rect')
    .attr('x', 90)
    .attr('y', 57)
    .attr('width', 5)
    .attr('height', 30)
    .attr('stroke', 'black')
    .attr('fill', 'black')

function table_flip(){
    let hinge = d3.interpolateString('rotate(0, 90, 90)', 'rotate(45, 90, 90)')
    let swingback = d3.interpolateString('rotate(45, 90, 90)', 'rotate(0, 90, 90)')
    table_top.transition()
        .attrTween('transform', function(d,i,a){return hinge})
        .duration(2000)
    leg_left.transition()
        .attrTween('transform', function(d,i,a){return hinge})
        .duration(2000)
    leg_right.transition()
        .attrTween('transform', function(d,i,a){return hinge})
        .duration(2000)


}

table_flip()

let table_top2 = svg5.append('rect')
    .attr('x', 20)
    .attr('y', 50)
    .attr('width', 75)
    .attr('height', 2)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let leg_left2 = svg5.append('rect')
    .attr('x', 20)
    .attr('y', 57)
    .attr('width', 5)
    .attr('height', 30)
    .attr('stroke', 'black')
    .attr('fill', 'black')
let leg_right2 = svg5.append('rect')
    .attr('x', 90)
    .attr('y', 57)
    .attr('width', 5)
    .attr('height', 30)
    .attr('stroke', 'black')
    .attr('fill', 'black')

function table_unflip(){
    let hinge = d3.interpolateString('rotate(0, 90, 90)', 'rotate(45, 90, 90)')
    let swingback = d3.interpolateString('rotate(45, 90, 90)', 'rotate(0, 90, 90)')
    table_top2.transition()
        .attrTween('transform', function(d,i,a){return swingback})
        .duration(2000)
    leg_left2.transition()
        .attrTween('transform', function(d,i,a){return swingback})
        .duration(2000)
    leg_right2.transition()
        .attrTween('transform', function(d,i,a){return swingback})
        .duration(2000)


}

table_unflip()